apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference
        image: registry.cn-beijing.aliyuncs.com/xsaopig/yolov5-inference-cpu
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        resources:
          requests:
            nvidia.com/gpu.shared: 1        # 请求 1 个 GPU
            cpu: "1"             # 请求 1 个 CPU
            memory: "5Gi"           # 请求 1Gi 内存
          limits:
            nvidia.com/gpu.shared: 1        # 限制为 1 个 GPU
            cpu: "2"                # 限制使用 1 个 CPU
            memory: "8Gi"           # 限制使用 2Gi 内存
        
---
apiVersion: v1
kind: Service
metadata:
  name: inference
spec:
  selector:
    app: inference
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
  type: ClusterIP
