apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-node
                operator: In
                values:
                - "true"
              - key: nvidia.com/cuda.runtime-version.full
                operator: In
                values:
                - "12.1"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nvidia.com/cuda.runtime-version.full
                operator: In
                values:
                - "12.1"
      containers:
      - name: inference-gpu
        image: registry.cn-beijing.aliyuncs.com/xsaopig/yolov5-inference-cu121
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        resources:
          requests:
            nvidia.com/gpu.shared: 1        # 请求 1 个 GPU
            cpu: "500m"                     # 请求 0.5 个 CPU
            memory: "5Gi"                   # 请求 5Gi 内存
          limits:
            nvidia.com/gpu.shared: 1        # 限制为 1 个 GPU
            cpu: "1"                        # 限制使用 1 个 CPU
            memory: "8Gi"                   # 限制使用 8Gi 内存
      - name: inference-cpu
        image: registry.cn-beijing.aliyuncs.com/xsaopig/yolov5-inference-cpu
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        resources:
          requests:
            nvidia.com/gpu.shared: 1        # 请求 1 个 GPU
            cpu: "1"             # 请求 1 个 CPU
            memory: "5Gi"           # 请求 1Gi 内存
          limits:
            nvidia.com/gpu.shared: 1        # 限制为 1 个 GPU
            cpu: "2"                # 限制使用 1 个 CPU
            memory: "8Gi"           # 限制使用 2Gi 内存
